import axios from 'axios'
import fs from 'fs'
import FormData from 'form-data'
import userModel from '../models/userModel.js'

// Controller function to generate image from prompt
// http://localhost:4000/api/image/generate-image
export const generateImage = async (req, res) => {

  try {

    const { userId, prompt } = req.body

    // Fetching User Details Using userId
    const user = await userModel.findById(userId)
    
    if (!user || !prompt) {
      return res.json({ success: false, message: 'Missing Details' })
    }

    // Checking User creditBalance
    if (user.creditBalance === 0 || user.creditBalance < 0) {
      return res.json({ success: false, message: 'No Credit Balance', creditBalance: user.creditBalance })
    }

    // Creation of new multi/part formdata
    const formdata = new FormData()
    formdata.append('prompt', prompt)

    // Calling Clipdrop API
    const { data } = await axios.post('https://clipdrop-api.co/text-to-image/v1', formdata, {
      headers: {
        'x-api-key': process.env.CLIPDROP_API,
      },
      responseType: "arraybuffer"
    })

    // Convertion of arrayBuffer to base64
    const base64Image = Buffer.from(data, 'binary').toString('base64');
    const resultImage = `data:image/png;base64,${base64Image}`

    // Generate image metadata
    const imageDetails = {
      source: 'AI Generated',
      generator: 'PicPrompt AI',
      prompt: prompt,
      generatedAt: new Date().toISOString(),
      copyright: 'This image is AI-generated and may be used for personal and commercial purposes, but check local laws for specific usage rights.',
      plagiarismStatus: 'AI-generated content - not subject to traditional plagiarism checks',
      usageRights: 'Free for personal and commercial use',
      attribution: 'Generated by PicPrompt AI'
    };

    // Deduction of user credit 
    await userModel.findByIdAndUpdate(user._id, { creditBalance: user.creditBalance - 1 })

    // Sending Response with image details
    res.json({ 
      success: true, 
      message: "Image Generated Successfully", 
      resultImage, 
      imageDetails,
      creditBalance: user.creditBalance - 1 
    })

  } catch (error) {
    console.log(error.message)
    res.json({ success: false, message: error.message })
  }
}